<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>unit</string>
	</array>
	<key>name</key>
	<string>C script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>&lt;(class)\s+(name)\s*=\s*("[A-Za-z]+[a-zA-Z0-9_]*")\s*(\s\s*(inherits)\s*=\s?("[A-Za-z]+(\.[a-zA-Z0-9]+)*")\s*)?&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.cscript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.namespace.cscript</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.cscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/(class)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class-definition.cscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.cscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.cscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.namespace.cscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type.cscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>&lt;(class)\s+(name)\s*=\s*("E[A-Za-z]+[a-zA-Z0-9_]*")\s\s*(inherits)\s*=\s*"(Exception)"\s*(/&gt;)</string>
					<key>name</key>
					<string>class.explicit-interface-implementation.cscript</string>
				</dict>
			</array>
		</dict>
		<key>file_block</key>
		<dict>
			<key>begin</key>
			<string>&lt;(unit)\s+(name)\s*=\s*("[A-Za-z]+[a-zA-Z0-9_]*")\s+(xmlns:xsi)=("_")\s+(xsi:type)=\s?("Unit")&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.cscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.cscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.namespace.cscript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.cscript</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.namespace.cscript</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.cscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/(unit)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.init-file.cscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.cscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.cscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.namespace.cscript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type.cscript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>&lt;(class)\s+(name)\s*=\s*("E[A-Za-z]+[a-zA-Z0-9_]*")\s\s*(inherits)\s*=\s*"(Exception)"\s*(/&gt;)</string>
					<key>name</key>
					<string>meta.exception-definition.cscript</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#file_block</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>&lt;(method)\s+(?&lt;kind definition&gt;(kind)\s*=\s*"\s*(list|lookup|update|insert|delete|dml)")?\s*(sign)\s*="\s*(?&lt;return type&gt;[a-zA-Z]{1}(\.?_*[a-zA-Z0-9]+)*(\[\])?\^?){1}\s*(?&lt;fuction name&gt;[a-zA-Z]{1}_*[_a-zA-Z0-9]*){1}\s*\(\s*(?&lt;params&gt;(?&lt;first param type&gt;[a-zA-Z]{1}(\.?_*[a-zA-Z0-9]+)*(\[\])?\^?){1}\s+(?&lt;first param name&gt;[a-zA-Z]{1}[_a-zA-Z0-9]*){1}(\s*,\s*(?&lt;param type&gt;([a-zA-Z]{1}(\.?_*[a-zA-Z0-9]+)*(\[\])?\^?))\s+(?&lt;param name&gt;[a-zA-Z]{1}[_a-zA-Z0-9]*))*\s*)?\)\s*"\s*(?&lt;mods definition&gt;mods\s*=\s*"\s*(virtual|spawn|queue)")?\s*\/?&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cscript</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>storage.type.cscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.cscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.cscript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.cscript</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.cscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/(method)&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.method-definition.cscript</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cscript</string>
	<key>uuid</key>
	<string>59de9fb4-446d-4b83-9d32-7312f12186dc</string>
</dict>
</plist>
